### ISSUE TITLE
Clarifications on protection policy

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/ops-manual#4]
The updated policy still causes some issues with its current wording, some examples below.

Teachers who are also SR volunteers. 
Volunteers who also run/attend other activities in their local area e.g. a Volunteer who mentors and also helps run scouting activities ect.

**Comment by richardbarlow** [comment]
On 5th October @didottyd suggested the following alternative wording (additions highlighted):

Volunteers must never **arrange to** meet with young people who are participating in Student Robotics activities outside of the supervised environment, or communicate over a channel
other than that **~~set up~~used** for group communication.

**Comment by richardbarlow** [comment]
@srobo/core-team Could you please review Diane's suggestions in the previous comment and also provide some worked examples where the current wording fails. Once we have these examples we can work towards a better wording that handles them all well.

**Comment by PeterJCLaw** [comment]
(speaking as an individual volunteer) The test case I think that we had previously was a team-leader who is also an SR volunteer. While clearly we want to enable team-leaders to also volunteer for SR it's not immediately clear that even the modified policy as proposed would allow that.

Test cases I can think of (both those at issue and those already supported, for completeness):
- team leaders who want to volunteer for SR (the case above)
- competitors who want to volunteer for SR (most likely by contributing to development things, as has happened, but I can also imagine a scenario where they mentor a team at another organisation)
- competitors where the team is of mixed ages (I'm not sure if we cover over-18s vs under-18s)
- volunteers who are also parents of competitors
- volunteers in their first of Uni who are still friends will competitors in the year below (likely due to having been at school with them, though the reason for this isn't really importnat and I can think of other legitimate reasons it might happen)

It might be beneficial to see what guidance other organisations provide their volunteers around this. For example the Scout Association has to cope with:
- leaders who are also parents of younger members
- young leaders (under 18s) who help with younger sections
- members who turn 18 while being a young leader and turn into leaders, and who clearly have existing friendships with a mixture of the other leaders and younger members

**Comment by Tyler-Ward** [comment]
Another case that isn't in Peters list is volunteers who are involved with multiple organisations e.g. mentoring for SR and also helping run a programming club. In this case inviting a team to also come along to the programming club would be prohibited under the suggested wording.

**Comment by didottyd** [comment]
I think in its current incarnation this issue is closed.
