### ISSUE TITLE
Clarify the Kit Service

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/ops-manual#5]
Not sure if this actually belongs in the ops manual, or is something to record elsewhere, however during the lead-up to SR2020 there has been some confusion (https://github.com/srobo/tasks/issues/325#issuecomment-541446765 and its reply https://github.com/srobo/tasks/issues/325#issuecomment-541460868) over how much of the kit handling should be done by each of the Competition and Kit teams.

While there now seems to be an agreement (https://github.com/srobo/tasks/issues/353#issuecomment-534929627 and its reply https://github.com/srobo/tasks/issues/353#issuecomment-535377105) that the Competition team will handle the kit moving for SR2020 Kickstart, we should clarify this before the competition event so that it is clear who should be handling the kits at that point.

**Comment by PeterJCLaw** [comment]
(replying as a comment with what I had thought the Kit Service would include)

Currently the Ops Manual states that the Kit Service includes:
> Recovering and checking kit following a competition cycle

To me this implies that the Kit Team will be organising at least the chasing of teams who fail to return kits at the competition, as well as possibly the return of kits from teams to SR at the competition. As the latter would need to fit into the activities at the competition, it may make sense for that to remain more flexible.

The ["Key Dates" document](https://docs.google.com/document/d/1hh-ByVaFs3Cy_zUZVkipeLUNMmKfSrjY3IvgSCgTqBQ/edit) has a point under the Kit Committee of "Deliver kits for KickStart". In discussion of that point it was noted that "kits would be delivered to where they need to be, to save moving them twice.", which seems to suggest that the Kit Team are responsible for at least getting the Kits to the Kickstart venues.
It may also therefore make sense for the Kit Team to then also be responsible for organising the handover of kits to the teams themselves, though as this needs to fit into the activities of the day it may make sense for this aspect to remain less defined.

**Comment by trickeydan** [comment]
@srobo/kit-committee I may have been mistaken. Please could somebody provide more clarity on this? I thought we took most of the kits to the container and weren't handling them from there.

If the kit team needs to handle recovery, then the competition team will need to share team information with us to enable that.

**Comment by TomWheal** [comment]
We are in the process of defining what the kit team is exactly responsible for currently, along with setting up the groups of people responsible for different areas. With this the ops manual will have a big overhaul.

It was agreed, verbally I believe, that the kit team would provide 40 kits to the competition team for this years competition. Due to the last minute planning of this alot of man hours have gone into this in a short period of time, meaning any more work by the kit team volenteers is unfeasible now, hence the agreement to have the kit ready in the container (or my garage) ready for kickstart. 

My take on the "deliver kits for kickstart" is us delivering kits to the competition team ready for kickstart. The main purpose of the kit team is to provide the kit service, what you do with the asset being  given to you doesn't really matter to the service provider as long as its given back. It is also out of the scope of the kit team to organised kickstart, which handing out the kits is the primary purpose of, in my opinion.

Also something to note, is in the future the plan is to get the kit ready and in the container at least a month before kickstart, in which case it wouldn't make sense for us to ship it to kickstart locations.

(If I had been asked to organised delivery to the kickstarts, which I never was, I only stated that it was out of scope in my opinion,  its possible something could have been organised, I had assumed that @RealOrangeOne agreeing that its apart of the competition team scope in  [srobo/tasks#353 (comment))](https://github.com/srobo/tasks/issues/353#issuecomment-535377105) would of actioned some work before now, instead of just leaving it to the last minute) 

I agree that documenting the scope is important, but just talking to each other is probably best to ensure that people know whats going on.

**Comment by PeterJCLaw** [comment]
For the avoidance of doubt: my intention here is _not_ to try to change what has been agreed for SR2020 Kickstart, but rather to raise that this needs clarifying after that point.

**Comment by RealOrangeOne** [comment]
The trustees just sent an email to the committees about this. The important points being:

> We, the trustees, were under the impression that it was the kit team who was responsible for getting kits to teams for the competition, including getting them to kickstarts (and volunteers at kickstarts distribute the kits) and also shipping them to remote destinations if required.

> So we would like to make it the responsibility of the kit team for all management of kits, including delivery to kickstarts and shipping to isolated teams, for replacement of damaged or broken kits elements during the competition season and for collecting and collating kits at the end of the season.

> We want to make it totally clear that the ownership of the kit lies with the kit team so they are responsible for delivering and collecting to school teams (not to the competition team).   We would expect kit team volunteers doing the sign out at kickstart and the kit checking at end of competition (+ chasing missing kit etc).  

@PeterJCLaw I believe this answers this issue (am happy to forward email around as necessary). I've asked the above be clarified in the ops manual.

**Comment by Scarzy** [comment]
This was updated shortly after the discussion. Closing
